# Generated by Django 5.0 on 2025-10-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('center_lat', models.FloatField()),
                ('center_lng', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
